name: search

include:
  - ../networks.yml

services:
  search.searxng:
    container_name: search.searxng
    hostname: search.searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - search-nw
    volumes:
      - ../storage/search/searxng/config:/etc/searxng:rw
      - ../storage/search/searxng/data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://search.searxng/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  #search.valkey:
  #  container_name: search.valkey
  #  hostname: search.valkey
  #  image: docker.io/valkey/valkey:8-alpine
  #  restart: unless-stopped
  #  command: valkey-server --save 30 1 --loglevel warning
  #  networks:
  #    - search-nw
  #  volumes:
  #    - ../storage/search/valkey:/data
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-size: "1m"
  #      max-file: "1"