name: search

include:
  - /own/docker/networks.yml

services:
  search.redis:
    container_name: search.redis
    hostname: search.redis
    image: docker.io/valkey/valkey:7-alpine
    restart: unless-stopped
    networks:
      - search-nw
    volumes:
      - ./storage/search/redis:/data
    command: valkey-server --save 30 1 --loglevel warning
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  search.searxng:
    container_name: search.searxng
    hostname: search.searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - search-nw
      - nginx-nw
    volumes:
      - ./storage/search/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://localhost/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"