name: wazuh

include:
  - /own/docker/networks.yml

services:
  wazuh.manager:
    container_name: wazuh.manager
    hostname: wazuh.manager
    image: wazuh/wazuh-manager:4.4.5
    restart: always
    networks:
      - wazuh-nw
    ports:
      - 1514:1514
      - 1515:1515
      - 514:514/udp
      #API- 55000:55000
    environment:
      - INDEXER_USERNAME=${WAZUH_INDEXER_USERNAME}
      - INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD}
      - DASHBOARD_USERNAME=${WAZUH_DASHBOARD_USERNAME}
      - DASHBOARD_PASSWORD=${WAZUH_DASHBOARD_PASSWORD}
      - API_USERNAME=${WAZUH_API_USERNAME}
      - API_PASSWORD=${WAZUH_API_PASSWORD}
      - INDEXER_URL=https://wazuh.indexer:9200
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    volumes:
      - ./storage/wazuh/mounts/wazuh_api_configuration:/var/ossec/api/configuration
      - ./storage/wazuh/mounts/wazuh_etc:/var/ossec/etc
      - ./storage/wazuh/mounts/wazuh_logs:/var/ossec/logs
      - ./storage/wazuh/mounts/wazuh_queue:/var/ossec/queue
      - ./storage/wazuh/mounts/wazuh_var_multigroups:/var/ossec/var/multigroups
      - ./storage/wazuh/mounts/wazuh_integrations:/var/ossec/integrations
      - ./storage/wazuh/mounts/wazuh_active_response:/var/ossec/active-response/bin
      - ./storage/wazuh/mounts/wazuh_agentless:/var/ossec/agentless
      - ./storage/wazuh/mounts/wazuh_wodles:/var/ossec/wodles
      - ./storage/wazuh/mounts/filebeat_etc:/etc/filebeat
      - ./storage/wazuh/mounts/filebeat_var:/var/lib/filebeat
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./storage/wazuh/config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
    tty: true
    stdin_open: true

  wazuh.indexer:
    container_name: wazuh.indexer
    hostname: wazuh.indexer
    image: wazuh/wazuh-indexer:4.4.5
    restart: always
    networks:
      - wazuh-nw
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1512m -Xmx1512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./storage/wazuh/mounts/wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ./storage/wazuh/config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./storage/wazuh/config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
    tty: true
    stdin_open: true

  wazuh.dashboard:
    container_name: wazuh.dashboard
    hostname: wazuh.dashboard
    image: wazuh/wazuh-dashboard:4.4.5
    restart: always
    networks:
      - wazuh-nw
    ports:
      - 10.0.0.1:500:5601
    environment:
      - INDEXER_USERNAME=${WAZUH_INDEXER_USERNAME}
      - INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD}
      - DASHBOARD_USERNAME=${WAZUH_DASHBOARD_USERNAME}
      - DASHBOARD_PASSWORD=${WAZUH_DASHBOARD_PASSWORD}
      - API_USERNAME=${WAZUH_API_USERNAME}
      - API_PASSWORD=${WAZUH_API_PASSWORD}
      - WAZUH_API_URL=https://wazuh.manager
    volumes:
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./storage/wazuh/config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./storage/wazuh/config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./storage/wazuh/config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager
    tty: true
    stdin_open: true