name: link

include:
  - ../networks.yml

services:
  link.backend:
    container_name: link.backend
    hostname: link.backend
    image: gq97a6/links
    restart: unless-stopped
    networks:
      - nginx-nw
      - mongodb-nw
    environment:
      SERVER_DOMAIN: link.hostunit.net
      SERVER_ORIGIN: https://link.hostunit.net
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017
      JWT_TOKEN_PRIMARY_EXPIRE: 300
      JWT_TOKEN_REFRESH_EXPIRE: 7200

  link.frontend:
    container_name: link.frontend
    hostname: link.frontend
    image: gq97a6/images:link_svelte-1.4.0
    restart: unless-stopped
    networks:
      - nginx-nw
