name: minecraft

include:
  - ../networks.yml

services:
  minecraft:
    container_name: minecraft
    hostname: minecraft
    image: itzg/minecraft-server
    restart: unless-stopped
    networks:
      - minecraft-nw
    ports:
      - 25565:25565
    volumes:
      - ../storage/minecraft/data:/data
    environment:
      TYPE: "VANILLA"
      MEMORY: "8G"
      EULA: "TRUE"
      VERSION: "1.16.5"
    tty: true
    stdin_open: true
