name: mongodb

include:
  - ../networks.yml

services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    restart: unless-stopped
    networks:
      - mongodb-nw
    ports:
      - 10.1.0.1:27017:27017
    volumes:
      - ../storage/mongodb/db:/data/db
      - ../storage/mongodb/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongoexpress:
    container_name: mongoexpress
    hostname: mongoexpress
    image: mongo-express
    restart: unless-stopped
    networks:
      - mongodb-nw
    ports:
      - 10.1.0.1:400:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
