name: nextchat

include:
  - ../networks.yml

services:
  nextchat:
    container_name: nextchat
    hostname: nextchat
    image: gq97a6/nextchat
    restart: unless-stopped
    networks:
      - nginx-nw
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      CODE: ${BASIC_PASSWORD}
      HIDE_USER_API_KEY: 1
      CUSTOM_MODELS: -all,gemini-2.5-flash-preview-04-17@Google=Gemini 2.5 Flash,gemini-2.5-pro-preview-03-25@Google=Gemini 2.5 Pro,claude-sonnet-4-20250514@Anthropic=Claude 4,claude-opus-4-20250514@Anthropic=Opus 4,claude-3-7-sonnet-latest@Anthropic=Claude 3.7,gpt-5@OpenAI,gpt-4o@OpenAI
      DEFAULT_MODEL: claude-3-7-sonnet-latest
      DEFAULT_INPUT_TEMPLATE: "test{{input}}"
