name: openvpn

include:
  - ../networks.yml

services:
  openvpn:
    container_name: openvpn
    hostname: openvpn
    image: gq97a6/openvpn
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ../storage/openvpn:/etc/openvpn
    environment:
      PUBLIC_IP: 116.203.211.100
      SUBNET_IP: 10.1.0.0
      SUBNET_MASK: 255.255.255.0
      SUBNET_CIDR: 10.1.0.0/24
      PORT: 1194
      PROTOCOL: udp
      ALLOW_INTERNET: false
    command: run-server
