name: proxy

include:
  - ../networks.yml

services:
  proxy:
    container_name: proxy
    hostname: proxy
    image: traefik:v3.3
    restart: unless-stopped
    networks:
      - proxy-nw
    ports:
      - 10.1.0.1:500:8080
      #- 80:80
      #- 443:443
    volumes:
      - ../storage/proxy:/etc/traefik/
      - /own/docker/storage/nginx/certs/alteratom.com/fullchain.pem:/certs/alteratom.com/fullchain.pem:ro
      - /own/docker/storage/nginx/certs/alteratom.com/privkey.pem:/certs/alteratom.com/privkey.pem:ro
      - /own/docker/storage/nginx/certs/hostunit.net/fullchain.pem:/certs/hostunit.net/fullchain.pem:ro
      - /own/docker/storage/nginx/certs/hostunit.net/privkey.pem:/certs/hostunit.net/privkey.pem:ro
    command: --configFile=/etc/traefik/traefik_static.yml
