name: terraria

include:
  - ../networks.yml

services:
  terraria:
    container_name: terraria
    hostname: terraria
    image: mcr.microsoft.com/dotnet/runtime:6.0
    restart: unless-stopped
    networks:
      - terraria-nw
      - mysql-nw
    ports:
      - 9999:9999
    volumes:
      - ../storage/terraria:/terraria
    command: /terraria/TShock.Server -config /terraria/config -configpath /terraria
