name: wazuh

include:
  - ../networks.yml

services:
  wazuh.manager:
    container_name: wazuh.manager
    hostname: wazuh.manager
    image: kalingth/wazuh-manager
    restart: always
    networks:
      - wazuh-nw
    ports:
      - 1514:1514
      - 1515:1515
      - 514:514/udp
      #API- 55000:55000
    environment:
      - INDEXER_USERNAME=${WAZUH_INDEXER_USERNAME}
      - INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD}
      - DASHBOARD_USERNAME=${WAZUH_DASHBOARD_USERNAME}
      - DASHBOARD_PASSWORD=${WAZUH_DASHBOARD_PASSWORD}
      - API_USERNAME=${WAZUH_API_USERNAME}
      - API_PASSWORD=${WAZUH_API_PASSWORD}
      - INDEXER_URL=https://wazuh.indexer:9200
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    tty: true
    stdin_open: true

  wazuh.indexer:
    container_name: wazuh.indexer
    hostname: wazuh.indexer
    image: kalingth/wazuh-indexer
    restart: always
    networks:
      - wazuh-nw
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1512m -Xmx1512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    tty: true
    stdin_open: true

  wazuh.dashboard:
    container_name: wazuh.dashboard
    hostname: wazuh.dashboard
    image: kalingth/wazuh-dashboard
    restart: always
    networks:
      - wazuh-nw
    ports:
      - 10.1.0.1:500:5601
    environment:
      - INDEXER_USERNAME=${WAZUH_INDEXER_USERNAME}
      - INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD}
      - DASHBOARD_USERNAME=${WAZUH_DASHBOARD_USERNAME}
      - DASHBOARD_PASSWORD=${WAZUH_DASHBOARD_PASSWORD}
      - API_USERNAME=${WAZUH_API_USERNAME}
      - API_PASSWORD=${WAZUH_API_PASSWORD}
      - WAZUH_API_URL=https://wazuh.manager
    depends_on:
      - wazuh.indexer
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager
    tty: true
    stdin_open: true